kind: pipeline
type: docker
name: main

platform:
  os: linux
  arch: amd64

workspace:
  base: /data/drone-go
  path: src/git.xiagaogao.com/coffee/base

volumes:
  - name: pkgdeps
    host:
      path: /data/drone/gocache/pkg
  - name: data
    host:
      path: /data

steps:
  - name: build
    image: golang:1.16
    environment:
      GOPROXY: https://goproxy.io
      GOPRIVATE: git.xiagaogao.com
      GOSUMDB: sum.golang.google.cn
      CGO_ENABLED: 0
    volumes:
      - name: pkgdeps
        path: /go/pkg
      - name: data
        path: /data
    commands:
      - ls -a /data
      - cat /data/netrc >> ~/.netrc
      - ln -s /data/gitconfig ~/.gitconfig
      - go mod tidy
    when:
      branch:
        include:
          - feature/*
          - master
          - develop
      event:
        include:
          - push
          - pull_request
