kind: pipeline
type: docker
name: main

platform:
  os: linux
  arch: amd64

workspace:
  base: /data/drone-go
  path: src/git.xiagaogao.com/coffee/base

steps:
  - name: build
    image: golang:1.16
    volumes:
      - '/data/drone:/data'
    commands:
      - ls -a /data
      - ls -a /data/drone-go
      - cat /data/netrc >> ~/.netrc
#      - ln -s /data/gitconfig ~/.gitconfig
      - go mod tidy
    when:
      branch:
        include:
          - feature/*
          - master
          - develop
      event:
        include:
          - push
          - pull_request
