kind: pipeline
type: exec
name: build

platform:
  os: linux
  arch: amd64

workspace:
  base: /root/drone-go
  path: src/git.xiagaogao.com/coffee/httpx

steps:
  - name: build
    environment:
      GOPROXY: https://goproxy.io
      GOPRIVATE: git.xiagaogao.com
      GOSUMDB: sum.golang.google.cn
    commands:
      - cat /root/.netrc >> ~/.netrc
      - ln -s /root/.gitconfig ~/.gitconfig
      - go mod tidy
    when:
      branch:
        include:
          - feature/*
          - master
          - dev
      event:
        include:
          - push
          - pull_request
  - name: notofy
    commands:
      - `curl -X POST -H 'Content-type: application/json' --data '{"text":"{{#success build.status}} build {{build.number}} succeeded. Good job.{{else}} build {{build.number}} failed. Fix me please.{{/success}}"}' https://hooks.slack.com/services/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`
