// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: encoder.proto

package log

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LogBody struct {
	Level                int32           `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Time                 int64           `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	LoggerName           string          `protobuf:"bytes,3,opt,name=logger_name,json=loggerName,proto3" json:"logger_name,omitempty"`
	Message              string          `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Stack                string          `protobuf:"bytes,5,opt,name=stack,proto3" json:"stack,omitempty"`
	Caller               *LogEntryCaller `protobuf:"bytes,6,opt,name=caller,proto3" json:"caller,omitempty"`
	Fields               string          `protobuf:"bytes,7,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LogBody) Reset()         { *m = LogBody{} }
func (m *LogBody) String() string { return proto.CompactTextString(m) }
func (*LogBody) ProtoMessage()    {}
func (*LogBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_624bf55293b3902a, []int{0}
}
func (m *LogBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogBody.Unmarshal(m, b)
}
func (m *LogBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogBody.Marshal(b, m, deterministic)
}
func (m *LogBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogBody.Merge(m, src)
}
func (m *LogBody) XXX_Size() int {
	return xxx_messageInfo_LogBody.Size(m)
}
func (m *LogBody) XXX_DiscardUnknown() {
	xxx_messageInfo_LogBody.DiscardUnknown(m)
}

var xxx_messageInfo_LogBody proto.InternalMessageInfo

func (m *LogBody) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LogBody) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LogBody) GetLoggerName() string {
	if m != nil {
		return m.LoggerName
	}
	return ""
}

func (m *LogBody) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LogBody) GetStack() string {
	if m != nil {
		return m.Stack
	}
	return ""
}

func (m *LogBody) GetCaller() *LogEntryCaller {
	if m != nil {
		return m.Caller
	}
	return nil
}

func (m *LogBody) GetFields() string {
	if m != nil {
		return m.Fields
	}
	return ""
}

type LogEntryCaller struct {
	Defined bool `protobuf:"varint,1,opt,name=defined,proto3" json:"defined,omitempty"`
	// PC       uintptr
	File                 string   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Line                 int32    `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Function             string   `protobuf:"bytes,4,opt,name=function,proto3" json:"function,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntryCaller) Reset()         { *m = LogEntryCaller{} }
func (m *LogEntryCaller) String() string { return proto.CompactTextString(m) }
func (*LogEntryCaller) ProtoMessage()    {}
func (*LogEntryCaller) Descriptor() ([]byte, []int) {
	return fileDescriptor_624bf55293b3902a, []int{1}
}
func (m *LogEntryCaller) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntryCaller.Unmarshal(m, b)
}
func (m *LogEntryCaller) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntryCaller.Marshal(b, m, deterministic)
}
func (m *LogEntryCaller) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntryCaller.Merge(m, src)
}
func (m *LogEntryCaller) XXX_Size() int {
	return xxx_messageInfo_LogEntryCaller.Size(m)
}
func (m *LogEntryCaller) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntryCaller.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntryCaller proto.InternalMessageInfo

func (m *LogEntryCaller) GetDefined() bool {
	if m != nil {
		return m.Defined
	}
	return false
}

func (m *LogEntryCaller) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *LogEntryCaller) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *LogEntryCaller) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func init() {
	proto.RegisterType((*LogBody)(nil), "base.log.LogBody")
	proto.RegisterType((*LogEntryCaller)(nil), "base.log.LogEntryCaller")
}

func init() { proto.RegisterFile("encoder.proto", fileDescriptor_624bf55293b3902a) }

var fileDescriptor_624bf55293b3902a = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x89, 0xdd, 0xfe, 0xd9, 0x59, 0xf4, 0x10, 0x44, 0x82, 0x17, 0xcb, 0x9e, 0x7a, 0x2a,
	0xa2, 0x6f, 0xb0, 0xe2, 0x6d, 0xf1, 0x90, 0xa3, 0x17, 0xc9, 0xb6, 0xd3, 0x10, 0x9c, 0x66, 0xa4,
	0xad, 0xc2, 0xbe, 0xa4, 0xcf, 0x24, 0x4d, 0x5a, 0x61, 0x6f, 0xdf, 0xef, 0x9b, 0x36, 0x99, 0x5f,
	0xe0, 0x1a, 0x7d, 0xc3, 0x2d, 0x0e, 0xf5, 0xd7, 0xc0, 0x13, 0xcb, 0xe2, 0x64, 0x46, 0xac, 0x89,
	0xed, 0xfe, 0x57, 0x40, 0x7e, 0x64, 0x7b, 0xe0, 0xf6, 0x2c, 0x6f, 0x21, 0x25, 0xfc, 0x41, 0x52,
	0xa2, 0x14, 0x55, 0xaa, 0x23, 0x48, 0x09, 0x9b, 0xc9, 0xf5, 0xa8, 0xae, 0x4a, 0x51, 0x25, 0x3a,
	0x64, 0xf9, 0x00, 0x3b, 0x62, 0x6b, 0x71, 0xf8, 0xf0, 0xa6, 0x47, 0x95, 0x94, 0xa2, 0xda, 0x6a,
	0x88, 0xd5, 0x9b, 0xe9, 0x51, 0x2a, 0xc8, 0x7b, 0x1c, 0x47, 0x63, 0x51, 0x6d, 0xc2, 0x70, 0xc5,
	0xf9, 0x92, 0x71, 0x32, 0xcd, 0xa7, 0x4a, 0x43, 0x1f, 0x41, 0x3e, 0x42, 0xd6, 0x18, 0x22, 0x1c,
	0x54, 0x56, 0x8a, 0x6a, 0xf7, 0xa4, 0xea, 0x75, 0xc3, 0xfa, 0xc8, 0xf6, 0xd5, 0x4f, 0xc3, 0xf9,
	0x25, 0xcc, 0xf5, 0xf2, 0x9d, 0xbc, 0x83, 0xac, 0x73, 0x48, 0xed, 0xa8, 0xf2, 0x70, 0xd0, 0x42,
	0x7b, 0x0f, 0x37, 0x97, 0x7f, 0xcc, 0xbb, 0xb4, 0xd8, 0x39, 0x8f, 0x6d, 0x10, 0x2b, 0xf4, 0x8a,
	0xb3, 0x5a, 0xe7, 0x28, 0xaa, 0x6d, 0x75, 0xc8, 0x73, 0x47, 0xce, 0x47, 0xa7, 0x54, 0x87, 0x2c,
	0xef, 0xa1, 0xe8, 0xbe, 0x7d, 0x33, 0x39, 0xf6, 0x8b, 0xce, 0x3f, 0x1f, 0xd2, 0xf7, 0x84, 0xd8,
	0x9e, 0xb2, 0xf0, 0xb0, 0xcf, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x10, 0x3a, 0xdc, 0x94, 0x69,
	0x01, 0x00, 0x00,
}
