// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: encoder.proto

package log

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LogBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level      int32           `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Time       int64           `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	LoggerName string          `protobuf:"bytes,3,opt,name=logger_name,json=loggerName,proto3" json:"logger_name,omitempty"`
	Message    string          `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Stack      string          `protobuf:"bytes,5,opt,name=stack,proto3" json:"stack,omitempty"`
	Caller     *LogEntryCaller `protobuf:"bytes,6,opt,name=caller,proto3" json:"caller,omitempty"`
	Fields     string          `protobuf:"bytes,7,opt,name=fields,proto3" json:"fields,omitempty"`
}

func (x *LogBody) Reset() {
	*x = LogBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encoder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBody) ProtoMessage() {}

func (x *LogBody) ProtoReflect() protoreflect.Message {
	mi := &file_encoder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBody.ProtoReflect.Descriptor instead.
func (*LogBody) Descriptor() ([]byte, []int) {
	return file_encoder_proto_rawDescGZIP(), []int{0}
}

func (x *LogBody) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LogBody) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *LogBody) GetLoggerName() string {
	if x != nil {
		return x.LoggerName
	}
	return ""
}

func (x *LogBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogBody) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

func (x *LogBody) GetCaller() *LogEntryCaller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *LogBody) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

type LogEntryCaller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Defined bool `protobuf:"varint,1,opt,name=defined,proto3" json:"defined,omitempty"`
	//    	PC       uintptr
	File     string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Line     int32  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Function string `protobuf:"bytes,4,opt,name=function,proto3" json:"function,omitempty"`
}

func (x *LogEntryCaller) Reset() {
	*x = LogEntryCaller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encoder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogEntryCaller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryCaller) ProtoMessage() {}

func (x *LogEntryCaller) ProtoReflect() protoreflect.Message {
	mi := &file_encoder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryCaller.ProtoReflect.Descriptor instead.
func (*LogEntryCaller) Descriptor() ([]byte, []int) {
	return file_encoder_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntryCaller) GetDefined() bool {
	if x != nil {
		return x.Defined
	}
	return false
}

func (x *LogEntryCaller) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *LogEntryCaller) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *LogEntryCaller) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

var File_encoder_proto protoreflect.FileDescriptor

var file_encoder_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1c, 0x73, 0x6d, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x6d, 0x73, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x22, 0xe2, 0x01,
	0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x63, 0x6b, 0x12, 0x44, 0x0a, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73, 0x6d, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x73, 0x6d, 0x73, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x61, 0x6c, 0x6c,
	0x65, 0x72, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x22, 0x6e, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x2e, 0x78, 0x69, 0x61, 0x67, 0x61, 0x6f,
	0x67, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x2f, 0x62,
	0x61, 0x73, 0x65, 0x2f, 0x6c, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encoder_proto_rawDescOnce sync.Once
	file_encoder_proto_rawDescData = file_encoder_proto_rawDesc
)

func file_encoder_proto_rawDescGZIP() []byte {
	file_encoder_proto_rawDescOnce.Do(func() {
		file_encoder_proto_rawDescData = protoimpl.X.CompressGZIP(file_encoder_proto_rawDescData)
	})
	return file_encoder_proto_rawDescData
}

var file_encoder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_encoder_proto_goTypes = []interface{}{
	(*LogBody)(nil),        // 0: smsservice.smsservicecommons.LogBody
	(*LogEntryCaller)(nil), // 1: smsservice.smsservicecommons.LogEntryCaller
}
var file_encoder_proto_depIdxs = []int32{
	1, // 0: smsservice.smsservicecommons.LogBody.caller:type_name -> smsservice.smsservicecommons.LogEntryCaller
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_encoder_proto_init() }
func file_encoder_proto_init() {
	if File_encoder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encoder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encoder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogEntryCaller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encoder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_encoder_proto_goTypes,
		DependencyIndexes: file_encoder_proto_depIdxs,
		MessageInfos:      file_encoder_proto_msgTypes,
	}.Build()
	File_encoder_proto = out.File
	file_encoder_proto_rawDesc = nil
	file_encoder_proto_goTypes = nil
	file_encoder_proto_depIdxs = nil
}
